POST http://localhost:9009/api/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZhc3lhIiwiZXhwIjoxNTg0NzgxMTQwfQ.24kaVe-tUkfUAgegL6ap_mwSSGKTAFuvfQlHsuNY3eg
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "name": "alif",
  "balance": 400,
  "owner_id": 4
}

###

# No admin list cards
GET http://localhost:9009/api/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IlBldHlhIiwiZXhwIjoxNTg0NzgxMTQwfQ.TYSVgKi94XIDtqIApWTh4cSObX57pCo38NU086YBjYM

###

# Yes Admin list cards
GET http://localhost:9009/api/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTg3MDQzNjc2LCJwaG9uZSI6OTExfQ.niFwAR260ybjfXsQ8794zUcmlOSdvDJOmddhUZrHBPk

### list cards id=1
GET http://localhost:9009/api/cards/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZhc3lhIiwiZXhwIjoxNTg0NzA5MDUwfQ.IH-UbER3ou6Hm1ECBwxDpmweLyOP7vBumFjrmoFMMw8

###
GET http://localhost:9009/api/cards/ownerid/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZhc3lhIiwicm9sZXMiOm51bGwsImV4cCI6MTU4NDY2MzMzMX0.UltpIFXFw_j8XU-0XYIu3fSkgCKvXOTL7_IyW5rXr4s
###

GET http://localhost:9009/api/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTg3MDQ3NTQ2LCJwaG9uZSI6OTExfQ.4YjSrOX2EKqQccSv_v_RTJA07RWvuuQ5ZAUp2hj4vBM

###

GET http://localhost:9009/api/cards/ownerid/1

###


POST http://localhost:9009/api/cards/transmoney
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTg3MjExNzg5LCJwaG9uZSI6OTExfQ.quDrWZbJwZcOsKNgus5jNJsxcOLxC6k435Sh7yAL_VE
Content-Type: application/json
Accept: application/json

{
  "id_card_sender": 1,
  "number_card_recipient": "2021600000000003",
  "count": 150
}

###



POST http://localhost:9009/api/cards/transmoney
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTg3MjExNzg5LCJwaG9uZSI6OTExfQ.quDrWZbJwZcOsKNgus5jNJsxcOLxC6k435Sh7yAL_VE
Content-Type: application/json
Accept: application/json

{
  "id_card_sender": 1,
  "number_card_recipient": "2021600000000003",
  "count": 150
}

###