POST http://localhost:9009/api/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZhc3lhIiwiZXhwIjoxNTg0NzgxMTQwfQ.24kaVe-tUkfUAgegL6ap_mwSSGKTAFuvfQlHsuNY3eg
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "name": "alif",
  "balance": 400,
  "owner_id": 4
}

###

# No admin list cards
GET http://localhost:9009/api/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IlBldHlhIiwiZXhwIjoxNTg0NzgxMTQwfQ.TYSVgKi94XIDtqIApWTh4cSObX57pCo38NU086YBjYM

###

# Yes Admin list cards
GET http://localhost:9009/api/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IlBldHlhIiwiZXhwIjoxNTg0NzA5MDUwfQ.5N3oREIhPW6gPo30GzStAGTus_F2nYQfBFzxi8zNX8I

### list cards id=1
GET http://localhost:9009/api/cards/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZhc3lhIiwiZXhwIjoxNTg0NzA5MDUwfQ.IH-UbER3ou6Hm1ECBwxDpmweLyOP7vBumFjrmoFMMw8

###
GET http://localhost:9009/api/cards/ownerid/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZhc3lhIiwicm9sZXMiOm51bGwsImV4cCI6MTU4NDY2MzMzMX0.UltpIFXFw_j8XU-0XYIu3fSkgCKvXOTL7_IyW5rXr4s
###

GET http://localhost:9009/api/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IlBldHlhIiwiZXhwIjoxNTg0Njg1NDAzfQ.-72pg0Axdjf06ayPxSzlGc6P_ZpV0xTDwdG3O2vDX6E

###

GET http://localhost:9009/api/cards/ownerid/1

###


POST http://localhost:9009/api/cards/transmoney/0
Content-Type: application/json
Accept: application/json

{
  "IdCardSender": 0,
  "NumberCardRecipient": "202160000000009",
  "Count": 150
}

###